### ISSUE TITLE
Selecting CLOB's?

### ISSUE THREAD

**Issue by corydoras** [mattn/go-oci8#26]
Should it be possible to select CLOB's? Im not sure if I am encountering a missing feature or a bug. What I am seeing when I try to select a clob is this:

    >  go run handbook-compare.go
    SIGBUS: bus error
    PC=0x5992514
    signal arrived during cgo execution

    runtime.cgocall(0x40015f0, 0x37bf1d98)
        /usr/local/go/src/pkg/runtime/cgocall.c:149 +0x10c fp=0x37bf1d8c
    github.com/mattn/go-oci8._Cfunc_OCIStmtFetch(0x40c0fa7c, 0x40be8ae0, 0x1, 0x2, 0x0, ...)
        github.com/mattn/go-oci8/_obj/_cgo_defun.c:169 +0x31 fp=0x37bf1d98
    github.com/mattn/go-oci8.(*OCI8Rows).Next(0x17b5b440, 0x17b5b480, 0x4, 0x4, 0x0, ...)
        /Users/jacob/Dropbox/go/src/github.com/mattn/go-oci8/oci8.go:592 +0x5a fp=0x37bf1e28
    database/sql.(*Rows).Next(0x17b5c0f0, 0x17b870b0)
        /usr/local/go/src/pkg/database/sql/sql.go:1509 +0xb1 fp=0x37bf1e54
    main.readSchemaXml(0x17b6f040, 0x40d2148, 0x7, 0x0, 0x0, ...)
        /Users/jacob/Dropbox/go/src/uom/handbook/feed/handbook-compare.go:54 +0x21a fp=0x37bf1f48
    main.main()
        /Users/jacob/Dropbox/go/src/uom/handbook/feed/handbook-compare.go:28 +0x196 fp=0x37bf1f98
    runtime.main()
        /usr/local/go/src/pkg/runtime/proc.c:220 +0xff fp=0x37bf1fcc
    runtime.goexit()
        /usr/local/go/src/pkg/runtime/proc.c:1394 fp=0x37bf1fd0

    goroutine 3 [chan receive]:
    database/sql.(*DB).connectionOpener(0x17b6f040)
        /usr/local/go/src/pkg/database/sql/sql.go:574 +0x3b
    created by database/sql.Open
        /usr/local/go/src/pkg/database/sql/sql.go:436 +0x1c7

    goroutine 4 [chan receive]:
    database/sql.(*DB).connectionOpener(0x17b6f080)
        /usr/local/go/src/pkg/database/sql/sql.go:574 +0x3b
    created by database/sql.Open
        /usr/local/go/src/pkg/database/sql/sql.go:436 +0x1c7

    goroutine 5 [syscall]:
    runtime.goexit()
        /usr/local/go/src/pkg/runtime/proc.c:1394

    eax     0x0
    ebx     0x34
    ecx     0x40c04870
    edx     0x40bfd160
    edi     0x40c0dea0
    esi     0x440
    ebp     0xbfff9988
    esp     0xbfff98a0
    eip     0x5992514
    eflags  0x10202
    cs      0x1b
    fs      0x0
    gs      0xf
    exit status 2

**Comment by mattn** [comment]
Should be fixed.

**Comment by ahdong2007** [comment]
It seems it's not fixed. I can only get the first 4000 characters when working with CLOB.

**Comment by MichaelS11** [comment]
@ahdong2007 Are you on the newest version?

If so and you are still having an issue, I would suggest opening up a new issue with minimal complete SQL, DDL, and Go code that reproduces the issue.
